version: "3.8"
services:
  postgres:
    container_name: postgres-flashcards
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postdb:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postdb:
